# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the master branch
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET Core (or the appropriate version you're using)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Change to the .NET version you're using

      # Step 3: Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build --configuration Release

      # Step 5: Publish the build (creates the executable)
      - name: Publish build
        run: dotnet publish --configuration Release --output ./publish

      # Step 6: Upload the build artifact (the build will be stored in ./publish)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: csharp-build
          path: ./publish
